import 'package:models/models.dart';

const List<Currency> currencies = <Currency>[
  Currency(
    entity: 'UNITED STATES OF AMERICA (THE)',
    currency: 'US Dollar',
    alphabeticCode: 'USD',
    numericCode: 840,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'CANADA',
    currency: 'Canadian Dollar',
    alphabeticCode: 'CAD',
    numericCode: 124,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'EUROPEAN UNION',
    currency: 'Euro',
    alphabeticCode: 'EUR',
    numericCode: 978,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'UKRAINE',
    currency: 'Hryvnia',
    alphabeticCode: 'UAH',
    numericCode: 980,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
    currency: 'Pound Sterling',
    alphabeticCode: 'GBP',
    numericCode: 826,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'POLAND',
    currency: 'Zloty',
    alphabeticCode: 'PLN',
    numericCode: 985,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'POLAND',
    currency: 'Zloty',
    alphabeticCode: 'PLZ',
    numericCode: 616,
    withdrawalDate: '1997-01',
  ),
  Currency(
    entity: 'AMERICAN SAMOA',
    currency: 'US Dollar',
    alphabeticCode: 'AMERICAN SAMOA USD',
    numericCode: 840,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'ANDORRA',
    currency: 'Euro',
    alphabeticCode: 'EUR',
    numericCode: 978,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'AFGHANISTAN',
    currency: 'Afghani',
    alphabeticCode: 'AFN',
    numericCode: 971,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'AFGHANISTAN',
    currency: 'Afghani',
    alphabeticCode: 'AFA',
    numericCode: 4,
    withdrawalDate: '2003-01',
  ),
  Currency(
    entity: 'ALBANIA',
    currency: 'Lek',
    alphabeticCode: 'ALL',
    numericCode: 8,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'ALBANIA',
    currency: 'Old Lek',
    alphabeticCode: 'ALK',
    numericCode: 8,
    withdrawalDate: '1989-12',
  ),
  Currency(
    entity: 'ALGERIA',
    currency: 'Algerian Dinar',
    alphabeticCode: 'DZD',
    numericCode: 12,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'ANDORRA',
    currency: 'Andorran Peseta',
    alphabeticCode: 'ADP',
    numericCode: 20,
    withdrawalDate: '2003-07',
  ),
  Currency(
    entity: 'ANDORRA',
    currency: 'Spanish Peseta',
    alphabeticCode: 'ESP',
    numericCode: 724,
    withdrawalDate: '2002-03',
  ),
  Currency(
    entity: 'ANDORRA',
    currency: 'French Franc',
    alphabeticCode: 'FRF',
    numericCode: 250,
    withdrawalDate: '2002-03',
  ),
  Currency(
    entity: 'ANGOLA',
    currency: 'Kwanza',
    alphabeticCode: 'AOA',
    numericCode: 973,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'ANGOLA',
    currency: 'Kwanza',
    alphabeticCode: 'AOK',
    numericCode: 24,
    withdrawalDate: '1991-03',
  ),
  Currency(
    entity: 'ANGOLA',
    currency: 'New Kwanza',
    alphabeticCode: 'AON',
    numericCode: 24,
    withdrawalDate: '2000-02',
  ),
  Currency(
    entity: 'ANGOLA',
    currency: 'Kwanza Reajustado',
    alphabeticCode: 'AOR',
    numericCode: 982,
    withdrawalDate: '2000-02',
  ),
  Currency(
    entity: 'ANGUILLA',
    currency: 'East Caribbean Dollar',
    alphabeticCode: 'XCD',
    numericCode: 951,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'ANTIGUA AND BARBUDA',
    currency: 'East Caribbean Dollar',
    alphabeticCode: 'XCD',
    numericCode: 951,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'ARGENTINA',
    currency: 'Argentine Peso',
    alphabeticCode: 'ARS',
    numericCode: 32,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'ARGENTINA',
    currency: 'Austral',
    alphabeticCode: 'ARA',
    numericCode: 32,
    withdrawalDate: '1992-01',
  ),
  Currency(
    entity: 'ARGENTINA',
    currency: 'Peso Argentino',
    alphabeticCode: 'ARP',
    numericCode: 32,
    withdrawalDate: '1985-07',
  ),
  Currency(
    entity: 'ARGENTINA',
    currency: 'Peso',
    alphabeticCode: 'ARY',
    numericCode: 32,
    withdrawalDate: '1989 to 1990',
  ),
  Currency(
    entity: 'ARMENIA',
    currency: 'Armenian Dram',
    alphabeticCode: 'AMD',
    numericCode: 51,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'ARMENIA',
    currency: 'Russian Ruble',
    alphabeticCode: 'RUR',
    numericCode: 810,
    withdrawalDate: '1994-08',
  ),
  Currency(
    entity: 'ARUBA',
    currency: 'Aruban Florin',
    alphabeticCode: 'AWG',
    numericCode: 533,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'AUSTRALIA',
    currency: 'Australian Dollar',
    alphabeticCode: 'AUD',
    numericCode: 36,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'AUSTRIA',
    currency: 'Euro',
    alphabeticCode: 'EUR',
    numericCode: 978,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'AUSTRIA',
    currency: 'Schilling',
    alphabeticCode: 'ATS',
    numericCode: 40,
    withdrawalDate: '2002-03',
  ),
  Currency(
    entity: 'AZERBAIJAN',
    currency: 'Azerbaijan Manat',
    alphabeticCode: 'AZN',
    numericCode: 944,
    minorUnit: 2,
    withdrawalDate: null,
  ),
  Currency(
    entity: 'AZERBAIJAN',
    currency: 'Azerbaijan Manat',
    alphabeticCode: 'AYM',
    numericCode: 945,
    withdrawalDate: '2005-10',
  ),
  Currency(
    entity: 'AZERBAIJAN',
    currency: 'Azerbaijanian Manat',
    alphabeticCode: 'AZM',
    numericCode: 31,
    withdrawalDate: null,
  ),
];
