// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'rates_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

RatesResponse _$RatesResponseFromJson(Map<String, dynamic> json) =>
    RatesResponse(
      cad: (json['CAD'] as num?)?.toInt(),
      aed: (json['AED'] as num?)?.toDouble(),
      afn: (json['AFN'] as num?)?.toDouble(),
      all: (json['ALL'] as num?)?.toDouble(),
      amd: (json['AMD'] as num?)?.toDouble(),
      ang: (json['ANG'] as num?)?.toDouble(),
      aoa: (json['AOA'] as num?)?.toDouble(),
      ars: (json['ARS'] as num?)?.toDouble(),
      aud: (json['AUD'] as num?)?.toDouble(),
      awg: (json['AWG'] as num?)?.toDouble(),
      azn: (json['AZN'] as num?)?.toDouble(),
      bam: (json['BAM'] as num?)?.toDouble(),
      bbd: (json['BBD'] as num?)?.toDouble(),
      bdt: (json['BDT'] as num?)?.toDouble(),
      bgn: (json['BGN'] as num?)?.toDouble(),
      bhd: (json['BHD'] as num?)?.toDouble(),
      bif: (json['BIF'] as num?)?.toDouble(),
      bmd: (json['BMD'] as num?)?.toDouble(),
      bnd: (json['BND'] as num?)?.toDouble(),
      bob: (json['BOB'] as num?)?.toDouble(),
      brl: (json['BRL'] as num?)?.toDouble(),
      bsd: (json['BSD'] as num?)?.toDouble(),
      btn: (json['BTN'] as num?)?.toDouble(),
      bwp: (json['BWP'] as num?)?.toDouble(),
      byn: (json['BYN'] as num?)?.toDouble(),
      bzd: (json['BZD'] as num?)?.toDouble(),
      cdf: (json['CDF'] as num?)?.toDouble(),
      chf: (json['CHF'] as num?)?.toDouble(),
      clp: (json['CLP'] as num?)?.toDouble(),
      cny: (json['CNY'] as num?)?.toDouble(),
      cop: (json['COP'] as num?)?.toDouble(),
      crc: (json['CRC'] as num?)?.toDouble(),
      cup: (json['CUP'] as num?)?.toDouble(),
      cve: (json['CVE'] as num?)?.toDouble(),
      czk: (json['CZK'] as num?)?.toDouble(),
      djf: (json['DJF'] as num?)?.toDouble(),
      dkk: (json['DKK'] as num?)?.toDouble(),
      dop: (json['DOP'] as num?)?.toDouble(),
      dzd: (json['DZD'] as num?)?.toDouble(),
      egp: (json['EGP'] as num?)?.toDouble(),
      ern: (json['ERN'] as num?)?.toDouble(),
      etb: (json['ETB'] as num?)?.toDouble(),
      eur: (json['EUR'] as num?)?.toDouble(),
      fjd: (json['FJD'] as num?)?.toDouble(),
      fkp: (json['FKP'] as num?)?.toDouble(),
      fok: (json['FOK'] as num?)?.toDouble(),
      gbp: (json['GBP'] as num?)?.toDouble(),
      gel: (json['GEL'] as num?)?.toDouble(),
      ggp: (json['GGP'] as num?)?.toDouble(),
      ghs: (json['GHS'] as num?)?.toDouble(),
      gip: (json['GIP'] as num?)?.toDouble(),
      gmd: (json['GMD'] as num?)?.toDouble(),
      gnf: (json['GNF'] as num?)?.toDouble(),
      gtq: (json['GTQ'] as num?)?.toDouble(),
      gyd: (json['GYD'] as num?)?.toDouble(),
      hkd: (json['HKD'] as num?)?.toDouble(),
      hnl: (json['HNL'] as num?)?.toDouble(),
      hrk: (json['HRK'] as num?)?.toDouble(),
      htg: (json['HTG'] as num?)?.toDouble(),
      huf: (json['HUF'] as num?)?.toDouble(),
      idr: (json['IDR'] as num?)?.toDouble(),
      ils: (json['ILS'] as num?)?.toDouble(),
      imp: (json['IMP'] as num?)?.toDouble(),
      inr: (json['INR'] as num?)?.toDouble(),
      iqd: (json['IQD'] as num?)?.toDouble(),
      irr: (json['IRR'] as num?)?.toDouble(),
      isk: (json['ISK'] as num?)?.toDouble(),
      jep: (json['JEP'] as num?)?.toDouble(),
      jmd: (json['JMD'] as num?)?.toDouble(),
      jod: (json['JOD'] as num?)?.toDouble(),
      jpy: (json['JPY'] as num?)?.toDouble(),
      kes: (json['KES'] as num?)?.toDouble(),
      kgs: (json['KGS'] as num?)?.toDouble(),
      khr: (json['KHR'] as num?)?.toDouble(),
      kid: (json['KID'] as num?)?.toDouble(),
      kmf: (json['KMF'] as num?)?.toDouble(),
      krw: (json['KRW'] as num?)?.toDouble(),
      kwd: (json['KWD'] as num?)?.toDouble(),
      kyd: (json['KYD'] as num?)?.toDouble(),
      kzt: (json['KZT'] as num?)?.toDouble(),
      lak: (json['LAK'] as num?)?.toDouble(),
      lbp: (json['LBP'] as num?)?.toDouble(),
      lkr: (json['LKR'] as num?)?.toDouble(),
      lrd: (json['LRD'] as num?)?.toDouble(),
      lsl: (json['LSL'] as num?)?.toInt(),
      lyd: (json['LYD'] as num?)?.toDouble(),
      mad: (json['MAD'] as num?)?.toDouble(),
      mdl: (json['MDL'] as num?)?.toDouble(),
      mga: (json['MGA'] as num?)?.toDouble(),
      mkd: (json['MKD'] as num?)?.toDouble(),
      mmk: (json['MMK'] as num?)?.toDouble(),
      mnt: (json['MNT'] as num?)?.toDouble(),
      mop: (json['MOP'] as num?)?.toDouble(),
      mru: (json['MRU'] as num?)?.toDouble(),
      mur: (json['MUR'] as num?)?.toDouble(),
      mvr: (json['MVR'] as num?)?.toDouble(),
      mwk: (json['MWK'] as num?)?.toDouble(),
      mxn: (json['MXN'] as num?)?.toDouble(),
      myr: (json['MYR'] as num?)?.toDouble(),
      mzn: (json['MZN'] as num?)?.toDouble(),
      nad: (json['NAD'] as num?)?.toInt(),
      ngn: (json['NGN'] as num?)?.toDouble(),
      nio: (json['NIO'] as num?)?.toDouble(),
      nok: (json['NOK'] as num?)?.toDouble(),
      npr: (json['NPR'] as num?)?.toDouble(),
      nzd: (json['NZD'] as num?)?.toDouble(),
      omr: (json['OMR'] as num?)?.toDouble(),
      pab: (json['PAB'] as num?)?.toDouble(),
      pen: (json['PEN'] as num?)?.toDouble(),
      pgk: (json['PGK'] as num?)?.toDouble(),
      php: (json['PHP'] as num?)?.toDouble(),
      pkr: (json['PKR'] as num?)?.toDouble(),
      pln: (json['PLN'] as num?)?.toDouble(),
      pyg: (json['PYG'] as num?)?.toDouble(),
      qar: (json['QAR'] as num?)?.toDouble(),
      ron: (json['RON'] as num?)?.toDouble(),
      rsd: (json['RSD'] as num?)?.toDouble(),
      rub: (json['RUB'] as num?)?.toDouble(),
      rwf: (json['RWF'] as num?)?.toDouble(),
      sar: (json['SAR'] as num?)?.toDouble(),
      sbd: (json['SBD'] as num?)?.toDouble(),
      scr: (json['SCR'] as num?)?.toDouble(),
      sdg: (json['SDG'] as num?)?.toDouble(),
      sek: (json['SEK'] as num?)?.toDouble(),
      sgd: (json['SGD'] as num?)?.toDouble(),
      shp: (json['SHP'] as num?)?.toDouble(),
      sle: (json['SLE'] as num?)?.toDouble(),
      sll: (json['SLL'] as num?)?.toDouble(),
      sos: (json['SOS'] as num?)?.toInt(),
      srd: (json['SRD'] as num?)?.toDouble(),
      ssp: (json['SSP'] as num?)?.toDouble(),
      stn: (json['STN'] as num?)?.toDouble(),
      syp: (json['SYP'] as num?)?.toDouble(),
      szl: (json['SZL'] as num?)?.toInt(),
      thb: (json['THB'] as num?)?.toDouble(),
      tjs: (json['TJS'] as num?)?.toDouble(),
      tmt: (json['TMT'] as num?)?.toDouble(),
      tnd: (json['TND'] as num?)?.toDouble(),
      top: (json['TOP'] as num?)?.toDouble(),
      ttd: (json['TTD'] as num?)?.toDouble(),
      tvd: (json['TVD'] as num?)?.toDouble(),
      twd: (json['TWD'] as num?)?.toDouble(),
      tzs: (json['TZS'] as num?)?.toDouble(),
      uah: (json['UAH'] as num?)?.toDouble(),
      ugx: (json['UGX'] as num?)?.toDouble(),
      usd: (json['USD'] as num?)?.toDouble(),
      uyu: (json['UYU'] as num?)?.toDouble(),
      uzs: (json['UZS'] as num?)?.toDouble(),
      ves: (json['VES'] as num?)?.toDouble(),
      vnd: (json['VND'] as num?)?.toDouble(),
      vuv: (json['VUV'] as num?)?.toDouble(),
      wst: (json['WST'] as num?)?.toDouble(),
      xaf: (json['XAF'] as num?)?.toDouble(),
      xcd: (json['XCD'] as num?)?.toDouble(),
      xdr: (json['XDR'] as num?)?.toDouble(),
      xof: (json['XOF'] as num?)?.toDouble(),
      xpf: (json['XPF'] as num?)?.toDouble(),
      yer: (json['YER'] as num?)?.toDouble(),
      zar: (json['ZAR'] as num?)?.toInt(),
      zmw: (json['ZMW'] as num?)?.toDouble(),
      zwl: (json['ZWL'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$RatesResponseToJson(RatesResponse instance) =>
    <String, dynamic>{
      'CAD': instance.cad,
      'AED': instance.aed,
      'AFN': instance.afn,
      'ALL': instance.all,
      'AMD': instance.amd,
      'ANG': instance.ang,
      'AOA': instance.aoa,
      'ARS': instance.ars,
      'AUD': instance.aud,
      'AWG': instance.awg,
      'AZN': instance.azn,
      'BAM': instance.bam,
      'BBD': instance.bbd,
      'BDT': instance.bdt,
      'BGN': instance.bgn,
      'BHD': instance.bhd,
      'BIF': instance.bif,
      'BMD': instance.bmd,
      'BND': instance.bnd,
      'BOB': instance.bob,
      'BRL': instance.brl,
      'BSD': instance.bsd,
      'BTN': instance.btn,
      'BWP': instance.bwp,
      'BYN': instance.byn,
      'BZD': instance.bzd,
      'CDF': instance.cdf,
      'CHF': instance.chf,
      'CLP': instance.clp,
      'CNY': instance.cny,
      'COP': instance.cop,
      'CRC': instance.crc,
      'CUP': instance.cup,
      'CVE': instance.cve,
      'CZK': instance.czk,
      'DJF': instance.djf,
      'DKK': instance.dkk,
      'DOP': instance.dop,
      'DZD': instance.dzd,
      'EGP': instance.egp,
      'ERN': instance.ern,
      'ETB': instance.etb,
      'EUR': instance.eur,
      'FJD': instance.fjd,
      'FKP': instance.fkp,
      'FOK': instance.fok,
      'GBP': instance.gbp,
      'GEL': instance.gel,
      'GGP': instance.ggp,
      'GHS': instance.ghs,
      'GIP': instance.gip,
      'GMD': instance.gmd,
      'GNF': instance.gnf,
      'GTQ': instance.gtq,
      'GYD': instance.gyd,
      'HKD': instance.hkd,
      'HNL': instance.hnl,
      'HRK': instance.hrk,
      'HTG': instance.htg,
      'HUF': instance.huf,
      'IDR': instance.idr,
      'ILS': instance.ils,
      'IMP': instance.imp,
      'INR': instance.inr,
      'IQD': instance.iqd,
      'IRR': instance.irr,
      'ISK': instance.isk,
      'JEP': instance.jep,
      'JMD': instance.jmd,
      'JOD': instance.jod,
      'JPY': instance.jpy,
      'KES': instance.kes,
      'KGS': instance.kgs,
      'KHR': instance.khr,
      'KID': instance.kid,
      'KMF': instance.kmf,
      'KRW': instance.krw,
      'KWD': instance.kwd,
      'KYD': instance.kyd,
      'KZT': instance.kzt,
      'LAK': instance.lak,
      'LBP': instance.lbp,
      'LKR': instance.lkr,
      'LRD': instance.lrd,
      'LSL': instance.lsl,
      'LYD': instance.lyd,
      'MAD': instance.mad,
      'MDL': instance.mdl,
      'MGA': instance.mga,
      'MKD': instance.mkd,
      'MMK': instance.mmk,
      'MNT': instance.mnt,
      'MOP': instance.mop,
      'MRU': instance.mru,
      'MUR': instance.mur,
      'MVR': instance.mvr,
      'MWK': instance.mwk,
      'MXN': instance.mxn,
      'MYR': instance.myr,
      'MZN': instance.mzn,
      'NAD': instance.nad,
      'NGN': instance.ngn,
      'NIO': instance.nio,
      'NOK': instance.nok,
      'NPR': instance.npr,
      'NZD': instance.nzd,
      'OMR': instance.omr,
      'PAB': instance.pab,
      'PEN': instance.pen,
      'PGK': instance.pgk,
      'PHP': instance.php,
      'PKR': instance.pkr,
      'PLN': instance.pln,
      'PYG': instance.pyg,
      'QAR': instance.qar,
      'RON': instance.ron,
      'RSD': instance.rsd,
      'RUB': instance.rub,
      'RWF': instance.rwf,
      'SAR': instance.sar,
      'SBD': instance.sbd,
      'SCR': instance.scr,
      'SDG': instance.sdg,
      'SEK': instance.sek,
      'SGD': instance.sgd,
      'SHP': instance.shp,
      'SLE': instance.sle,
      'SLL': instance.sll,
      'SOS': instance.sos,
      'SRD': instance.srd,
      'SSP': instance.ssp,
      'STN': instance.stn,
      'SYP': instance.syp,
      'SZL': instance.szl,
      'THB': instance.thb,
      'TJS': instance.tjs,
      'TMT': instance.tmt,
      'TND': instance.tnd,
      'TOP': instance.top,
      'TTD': instance.ttd,
      'TVD': instance.tvd,
      'TWD': instance.twd,
      'TZS': instance.tzs,
      'UAH': instance.uah,
      'UGX': instance.ugx,
      'USD': instance.usd,
      'UYU': instance.uyu,
      'UZS': instance.uzs,
      'VES': instance.ves,
      'VND': instance.vnd,
      'VUV': instance.vuv,
      'WST': instance.wst,
      'XAF': instance.xaf,
      'XCD': instance.xcd,
      'XDR': instance.xdr,
      'XOF': instance.xof,
      'XPF': instance.xpf,
      'YER': instance.yer,
      'ZAR': instance.zar,
      'ZMW': instance.zmw,
      'ZWL': instance.zwl,
    };
